server:
  port: 8090

spring:
    datasource:
       url: jdbc:postgresql://172.29.112.1:5432/finology_car
       username: postgres
       password: Shkna1368


    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      database: POSTGRESQL
      hibernate:
       ddl-auto: create
